/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silo;

import com.silo.controller.DeliveringOrderCtl;

public class DeliveryNoteDesc extends javax.swing.JFrame {
    private DeliveringOrderCtl deliveringOrderCtl;
    
    public DeliveryNoteDesc() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceDescription = new javax.swing.JPanel();
        invoiceNumberLabel = new javax.swing.JLabel();
        deliveryNoteNumberLabel = new javax.swing.JLabel();
        deliveryCustomerNameLabel = new javax.swing.JLabel();
        deliveryNoteOrderDateLabel = new javax.swing.JLabel();
        deliveryNoteDeliveryDateLabel = new javax.swing.JLabel();
        deliveryNoteStatusLabel = new javax.swing.JLabel();
        invoiceNumberLabelFill = new javax.swing.JLabel();
        deliveryNoteNumberLabelFill = new javax.swing.JLabel();
        deliveryCustomerNameLabelFill = new javax.swing.JLabel();
        deliveryNoteOrderDateLabelFill = new javax.swing.JLabel();
        deliveryNoteDeliveryDateFill = new javax.swing.JLabel();
        deliveryNoteStatusLabelFill = new javax.swing.JLabel();
        preparingButton = new javax.swing.JButton();
        signButton = new javax.swing.JButton();
        signButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoiceNumberLabel.setText("Invoice Number");
        invoiceNumberLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        deliveryNoteNumberLabel.setText("Delivery Note No.");
        deliveryNoteNumberLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        deliveryCustomerNameLabel.setText("Customer Name");
        deliveryCustomerNameLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        deliveryNoteOrderDateLabel.setText("Order Date");
        deliveryNoteOrderDateLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        deliveryNoteDeliveryDateLabel.setText("Delivery Date");
        deliveryNoteDeliveryDateLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        deliveryNoteStatusLabel.setText("Status");
        deliveryNoteStatusLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        invoiceNumberLabelFill.setPreferredSize(new java.awt.Dimension(200, 16));

        deliveryNoteNumberLabelFill.setPreferredSize(new java.awt.Dimension(200, 16));

        deliveryCustomerNameLabelFill.setPreferredSize(new java.awt.Dimension(200, 16));

        deliveryNoteOrderDateLabelFill.setPreferredSize(new java.awt.Dimension(200, 16));

        deliveryNoteDeliveryDateFill.setPreferredSize(new java.awt.Dimension(200, 16));

        deliveryNoteStatusLabelFill.setPreferredSize(new java.awt.Dimension(200, 16));

        preparingButton.setText("Preparing");
        preparingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onPreparingButtonClick(evt);
            }
        });

        signButton.setText("Sign");
        signButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onSignButtonClick(evt);
            }
        });

        signButton1.setText("Pending");
        signButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onPendingButtonClick(evt);
            }
        });

        javax.swing.GroupLayout invoiceDescriptionLayout = new javax.swing.GroupLayout(invoiceDescription);
        invoiceDescription.setLayout(invoiceDescriptionLayout);
        invoiceDescriptionLayout.setHorizontalGroup(
            invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(invoiceDescriptionLayout.createSequentialGroup()
                        .addComponent(deliveryNoteDeliveryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deliveryNoteDeliveryDateFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoiceDescriptionLayout.createSequentialGroup()
                        .addComponent(deliveryNoteOrderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deliveryNoteOrderDateLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoiceDescriptionLayout.createSequentialGroup()
                        .addComponent(deliveryCustomerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deliveryCustomerNameLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoiceDescriptionLayout.createSequentialGroup()
                        .addComponent(deliveryNoteNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deliveryNoteNumberLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoiceDescriptionLayout.createSequentialGroup()
                        .addComponent(invoiceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(invoiceNumberLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceDescriptionLayout.createSequentialGroup()
                        .addComponent(deliveryNoteStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preparingButton)
                            .addComponent(deliveryNoteStatusLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        invoiceDescriptionLayout.setVerticalGroup(
            invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceNumberLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryNoteNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryNoteNumberLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryCustomerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryCustomerNameLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryNoteOrderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryNoteOrderDateLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryNoteDeliveryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryNoteDeliveryDateFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoiceDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryNoteStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryNoteStatusLabelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(preparingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoiceDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoiceDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onPreparingButtonClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onPreparingButtonClick
        // TODO add your handling code here:
        prepareDeliveryNote();
    }//GEN-LAST:event_onPreparingButtonClick
    
    private void prepareDeliveryNote(){
        deliveringOrderCtl.changeDNStatus(deliveringOrderCtl.getDaftarSJCtl().getMainPage().getEditedId(), "preparing");
    }
    
    private void onSignButtonClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onSignButtonClick
        // TODO add your handling code here:
        signDeliveryNote();
    }//GEN-LAST:event_onSignButtonClick

    private void signDeliveryNote(){
        deliveringOrderCtl.changeDNStatus(deliveringOrderCtl.getDaftarSJCtl().getMainPage().getEditedId(), "completed");
    }
    
    private void onPendingButtonClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onPendingButtonClick
        // TODO add your handling code here:
        pendingDeliveryNote();
    }//GEN-LAST:event_onPendingButtonClick

    private void pendingDeliveryNote(){
        deliveringOrderCtl.changeDNStatus(deliveringOrderCtl.getDaftarSJCtl().getMainPage().getEditedId(), "pending");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deliveryCustomerNameLabel;
    private javax.swing.JLabel deliveryCustomerNameLabelFill;
    private javax.swing.JLabel deliveryNoteDeliveryDateFill;
    private javax.swing.JLabel deliveryNoteDeliveryDateLabel;
    private javax.swing.JLabel deliveryNoteNumberLabel;
    private javax.swing.JLabel deliveryNoteNumberLabelFill;
    private javax.swing.JLabel deliveryNoteOrderDateLabel;
    private javax.swing.JLabel deliveryNoteOrderDateLabelFill;
    private javax.swing.JLabel deliveryNoteStatusLabel;
    private javax.swing.JLabel deliveryNoteStatusLabelFill;
    private javax.swing.JPanel invoiceDescription;
    private javax.swing.JLabel invoiceNumberLabel;
    private javax.swing.JLabel invoiceNumberLabelFill;
    private javax.swing.JButton preparingButton;
    private javax.swing.JButton signButton;
    private javax.swing.JButton signButton1;
    // End of variables declaration//GEN-END:variables
    
    public void setDeliveryNoteDescriptionLabel(String invoiceNumber, String deliveryNoteNumber, String customerName, String orderDate, String deliveryDate, String status){
        invoiceNumberLabelFill.setText(invoiceNumber);
        deliveryNoteNumberLabelFill.setText(deliveryNoteNumber);
        deliveryCustomerNameLabelFill.setText(customerName);
        deliveryNoteOrderDateLabelFill.setText(orderDate);
        deliveryNoteDeliveryDateFill.setText(deliveryDate);
        deliveryNoteStatusLabelFill.setText(status);
    }

    public void setDeliveringOrderCtl(DeliveringOrderCtl deliveringOrderCtl) {
        this.deliveringOrderCtl = deliveringOrderCtl;
        this.deliveringOrderCtl.setDeliveryNoteDesc(this);
    }
}
