/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silo;

import com.silo.controller.CreateDNCtl;

public class DeliveryNoteForm extends javax.swing.JFrame {
    
    private CreateDNCtl createDNCtl;
    
    public DeliveryNoteForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliveryNoteForm = new javax.swing.JPanel();
        invoiceNumberLabel = new javax.swing.JLabel();
        invoiceNumberTF = new javax.swing.JTextField();
        deliveryNoteNumberLabel = new javax.swing.JLabel();
        deliveryNoteNumberTF = new javax.swing.JTextField();
        customerNameLabel = new javax.swing.JLabel();
        orderDateLabel = new javax.swing.JLabel();
        deliveryDateLabel = new javax.swing.JLabel();
        orderDateTF = new javax.swing.JTextField();
        deliveryDateTF = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        customerNameTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoiceNumberLabel.setText("Invoice Number");
        invoiceNumberLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        invoiceNumberTF.setPreferredSize(new java.awt.Dimension(200, 22));

        deliveryNoteNumberLabel.setText("Delivery Note No.");
        deliveryNoteNumberLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        deliveryNoteNumberTF.setPreferredSize(new java.awt.Dimension(200, 22));

        customerNameLabel.setText("Customer Name");
        customerNameLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        orderDateLabel.setText("Order Date");
        orderDateLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        deliveryDateLabel.setText("Delivery Date");
        deliveryDateLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        orderDateTF.setPreferredSize(new java.awt.Dimension(200, 22));

        deliveryDateTF.setPreferredSize(new java.awt.Dimension(200, 22));

        createButton.setText("Create");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onCreateButtonClick(evt);
            }
        });

        customerNameTF.setPreferredSize(new java.awt.Dimension(200, 22));

        javax.swing.GroupLayout deliveryNoteFormLayout = new javax.swing.GroupLayout(deliveryNoteForm);
        deliveryNoteForm.setLayout(deliveryNoteFormLayout);
        deliveryNoteFormLayout.setHorizontalGroup(
            deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryNoteFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryNoteFormLayout.createSequentialGroup()
                        .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryNoteNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryNoteNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deliveryNoteFormLayout.createSequentialGroup()
                        .addComponent(invoiceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(invoiceNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryNoteFormLayout.createSequentialGroup()
                        .addComponent(deliveryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createButton)
                            .addComponent(deliveryDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        deliveryNoteFormLayout.setVerticalGroup(
            deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryNoteFormLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryNoteNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryNoteNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deliveryNoteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createButton)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deliveryNoteForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deliveryNoteForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onCreateButtonClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onCreateButtonClick
        // TODO add your handling code here:
        showConfirmationMessage();
    }//GEN-LAST:event_onCreateButtonClick
    
    private void showConfirmationMessage(){
        createDNCtl.openConfirmationMessage("Create new delivery note?");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTF;
    private javax.swing.JLabel deliveryDateLabel;
    private javax.swing.JTextField deliveryDateTF;
    private javax.swing.JPanel deliveryNoteForm;
    private javax.swing.JLabel deliveryNoteNumberLabel;
    private javax.swing.JTextField deliveryNoteNumberTF;
    private javax.swing.JLabel invoiceNumberLabel;
    private javax.swing.JTextField invoiceNumberTF;
    private javax.swing.JLabel orderDateLabel;
    private javax.swing.JTextField orderDateTF;
    // End of variables declaration//GEN-END:variables

    public String getInvoiceNumberTF(){
        return invoiceNumberTF.getText();
    }
    
    public String getDeliveryNoteNumberTF(){
        return deliveryNoteNumberTF.getText();
    }
    
    public String getCustomerNameTF(){
        return customerNameTF.getText();
    }
    
    public String getOrderDateTF(){
        return orderDateTF.getText();
    }
    
    public String getDeliveryDateTF(){
        return deliveryDateTF.getText();
    }

    public void setCreateDNCtl(CreateDNCtl createDNCtl) {
        this.createDNCtl = createDNCtl;
        this.createDNCtl.setDeliveryNoteForm(this);
    }
    
    public void setTextField(){
        invoiceNumberTF.setText("");
        deliveryNoteNumberTF.setText("");
        customerNameTF.setText("");
        orderDateTF.setText("");
        deliveryDateTF.setText("");
    }
}
