/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silo;

/**
 *
 * @author user
 */
public class ItemForm extends javax.swing.JFrame {

    /**
     * Creates new form ItemForm
     */
    public ItemForm() {
        initComponents();
        
        itemDescriptionTF.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemForm = new javax.swing.JPanel();
        itemBarcodeLabel = new javax.swing.JLabel();
        itemBarcodeTF = new javax.swing.JTextField();
        itemTitleLabel = new javax.swing.JLabel();
        itemTitleTF = new javax.swing.JTextField();
        itemDescriptionLabel = new javax.swing.JLabel();
        itemManufacturerLabel = new javax.swing.JLabel();
        itemUrlLabel = new javax.swing.JLabel();
        itemDescriptionPane = new javax.swing.JScrollPane();
        itemDescriptionTF = new javax.swing.JTextArea();
        itemManufacturerTF = new javax.swing.JTextField();
        itemUrlTF = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        itemStockLabel = new javax.swing.JLabel();
        itemStockTF = new javax.swing.JTextField();
        itemIdLabel2 = new javax.swing.JLabel();
        itemIdLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        itemBarcodeLabel.setText("Barcode");
        itemBarcodeLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        itemBarcodeTF.setPreferredSize(new java.awt.Dimension(200, 22));
        itemBarcodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBarcodeTFActionPerformed(evt);
            }
        });

        itemTitleLabel.setText("Title");
        itemTitleLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        itemTitleTF.setPreferredSize(new java.awt.Dimension(200, 22));
        itemTitleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTitleTFActionPerformed(evt);
            }
        });

        itemDescriptionLabel.setText("Description");
        itemDescriptionLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        itemManufacturerLabel.setText("Manufacturer");
        itemManufacturerLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        itemUrlLabel.setText("URL");
        itemUrlLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        itemDescriptionTF.setColumns(20);
        itemDescriptionTF.setRows(5);
        itemDescriptionPane.setViewportView(itemDescriptionTF);

        itemManufacturerTF.setPreferredSize(new java.awt.Dimension(200, 22));
        itemManufacturerTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManufacturerTFActionPerformed(evt);
            }
        });

        itemUrlTF.setPreferredSize(new java.awt.Dimension(200, 22));
        itemUrlTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUrlTFActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onSubmitButtonClick(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        itemStockLabel.setText("Number of Stock");
        itemStockLabel.setPreferredSize(new java.awt.Dimension(100, 22));

        itemStockTF.setPreferredSize(new java.awt.Dimension(200, 22));
        itemStockTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStockTFActionPerformed(evt);
            }
        });

        itemIdLabel2.setPreferredSize(new java.awt.Dimension(100, 22));

        itemIdLabel1.setText("Id");
        itemIdLabel1.setPreferredSize(new java.awt.Dimension(100, 22));

        javax.swing.GroupLayout itemFormLayout = new javax.swing.GroupLayout(itemForm);
        itemForm.setLayout(itemFormLayout);
        itemFormLayout.setHorizontalGroup(
            itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemFormLayout.createSequentialGroup()
                        .addComponent(itemStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemStockTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itemFormLayout.createSequentialGroup()
                        .addComponent(itemUrlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemUrlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itemFormLayout.createSequentialGroup()
                        .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemManufacturerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemDescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemManufacturerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemTitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(itemFormLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(submitButton))
                    .addGroup(itemFormLayout.createSequentialGroup()
                        .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemBarcodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemIdLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemIdLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemBarcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        itemFormLayout.setVerticalGroup(
            itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemIdLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemIdLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemBarcodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemBarcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemTitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemDescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemManufacturerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemManufacturerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemUrlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemUrlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemStockTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(submitButton)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBarcodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBarcodeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBarcodeTFActionPerformed

    private void itemTitleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTitleTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTitleTFActionPerformed

    private void itemManufacturerTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManufacturerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemManufacturerTFActionPerformed

    private void itemUrlTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUrlTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUrlTFActionPerformed

    private void itemStockTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStockTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemStockTFActionPerformed

    private void onSubmitButtonClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onSubmitButtonClick
        // TODO add your handling code here:
    }//GEN-LAST:event_onSubmitButtonClick

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemBarcodeLabel;
    private javax.swing.JTextField itemBarcodeTF;
    private javax.swing.JLabel itemDescriptionLabel;
    private javax.swing.JScrollPane itemDescriptionPane;
    private javax.swing.JTextArea itemDescriptionTF;
    private javax.swing.JPanel itemForm;
    private javax.swing.JLabel itemIdLabel1;
    private javax.swing.JLabel itemIdLabel2;
    private javax.swing.JLabel itemManufacturerLabel;
    private javax.swing.JTextField itemManufacturerTF;
    private javax.swing.JLabel itemStockLabel;
    private javax.swing.JTextField itemStockTF;
    private javax.swing.JLabel itemTitleLabel;
    private javax.swing.JTextField itemTitleTF;
    private javax.swing.JLabel itemUrlLabel;
    private javax.swing.JTextField itemUrlTF;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
